### ISSUE TITLE
[RFC] Deciding framework for discord service 

### ISSUE THREAD

**Issue by Ajeyakrishna-k** [Real-Dev-Squad/discord-service#11]
##### Design doc: https://docs.google.com/document/d/1Nv-qQ9pe_feX_ELkifmhsSKCSgM_uid0Sz95wBXZMHA/edit

This will be a small service with one route exposed and mainly focused on calling discord API's. My suggestion would be to build it in TS using NEST.js framework. 
- TS because we already have some discord API integration code in TS written for Discord slash commands which can be reused. 
- Nest.js as it was most of the common libraries required built in and less time would be wasted deciding other libraries. Also we are not using nest.js in any other service. So this will be a good edition. 

Other frameworks that we can choose: 
- Express.js
- Koa
- Fastify

**Comment by joyguptaa** [comment]
Closing this as the tech stack has been decided.
